server:
  port: 8090
spring:
  config:
    activate:
      on-profile: "qa"
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
build:
  version: "2.0"

loans:
  message: "Welcome to Bank loans related QA APIs "
  contactDetails:
    name: "Cyrano Marita -  QA Lead"
    email: "cyrano@mantletechsolutions.com"
  onCallSupport:
    - (+44) 785 545-6565
    - (+44) 853 546-3467
